In [7]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
y = [1,2,3,4]
print(y)
print(type(y))


[1, 2, 3, 4]
<class 'list'>


In [9]:
%timeit [j**4 for j in range(1,9)]

281 ns ± 3.88 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
import numpy as np

%timeit np.arange(1,9)**4

767 ns ± 13.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Array :
To create a NumPy array , you can use the funciton np.array() .


In [19]:
import numpy as np

x = [1,2,3,4,5]
y = np.array(x)

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [18]:
l = []
for i in range(1, 5):
    int_1 = int(input("Enter the Integer :"))
    l.append(int_1)

print(np.array(l))    

[11 12 13 14]


In [20]:
#2d array :

ar2 = np.array([[1,2,3,4],[4,5,6,7]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [4 5 6 7]]
2


In [24]:
#3d array :
ar3 = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
3


In [12]:
import numpy as np

#multi dimesional array :
ar2 = np.array([1, 2, 3, 4, 5], ndmin=10)
print(ar2)
print(ar2.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10
